version: '3.6'

services:

  proxy:
    image: nginx
    container_name: proxy
    restart: always
    volumes:
      - "./proxy/nginx:/etc/nginx/"
      - "/var/log/nginx:/var/log/nginx"
    ports:
      - "993:993"
      - "465:465"
      - "143:143"
      - "25:25"
